export interface PaperConfig {
  id: string
  title: string
  subtitle: string
  abstract: string
  pdfUrl: string
  latexUrl?: string
  githubUrl: string
  date: string
  authors: string[]
  tags: string[]
  relatedLinks?: {
    label: string
    url: string
  }[]
}

export interface SiteConfig {
  name: string
  fullName: string
  description: string
  website: string
  github: string
  primaryColor: string
  secondaryColor: string
  accentColor: string
  logo: string
  papers: PaperConfig[]
}

export const siteConfig: SiteConfig = {
  name: 'Zoo Labs',
  fullName: 'Zoo Labs Foundation (501c3)',
  description: 'Democratizing AI through decentralized training and open source frontier models',
  website: 'https://zoo.ngo',
  github: 'https://github.com/zooai',
  primaryColor: '#2ECC71',
  secondaryColor: '#27AE60',
  accentColor: '#F39C12',
  logo: '/logos/zoo-logo.svg',
  papers: [
    {
      id: 'foundation-mission',
      title: 'Zoo Labs Foundation Mission',
      subtitle: 'AI-Blockchain Research for Conservation, Education, and Science',
      abstract: '501(c)(3) non-profit mission: Conservation AI, Educational AI, and Frontier AI research for the public good.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-foundation-mission.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-foundation-mission.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-01-15',
      authors: ['Zoo Labs Foundation'],
      tags: ['Foundation', 'Conservation', 'Education', 'Mission'],
    },
    {
      id: 'network-architecture',
      title: 'Zoo Network Architecture',
      subtitle: 'Decentralized AI Training and Inference Layer',
      abstract: 'L2 AI specialization layer with HLLM integration and federated learning for decentralized training and inference.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-network-architecture.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-network-architecture.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-10-01',
      authors: ['Zoo Labs Foundation'],
      tags: ['Architecture', 'L2', 'Federated Learning'],
    },
    {
      id: 'tokenomics',
      title: 'Zoo Tokenomics',
      subtitle: '100% Airdrop Community-Owned AI Infrastructure',
      abstract: '100% airdrop tokenomics with zero VC/private sales and democratic validator participation for community-owned AI.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-tokenomics.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-tokenomics.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-10-15',
      authors: ['Zoo Labs Foundation'],
      tags: ['Tokenomics', 'Airdrop', 'DAO Governance'],
    },
    {
      id: 'gym-training-platform',
      title: 'Gym: Democratizing AI Model Training',
      subtitle: 'Open-Source Training Infrastructure',
      abstract: 'Comprehensive open-source platform supporting 100+ models and 8 training methods for democratized AI training.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/gym-training-platform.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/gym-training-platform.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-09-01',
      authors: ['Zoo Labs Foundation'],
      tags: ['Gym', 'Training', 'Open Source'],
    },
    {
      id: 'hllm-training-free-grpo',
      title: 'HLLM: Hamiltonian LLMs with Training-Free GRPO',
      subtitle: '99.8% Cost Reduction via Semantic Optimization',
      abstract: '99.8% cost reduction ($18 vs $10,000+) and +2.7% accuracy via semantic optimization with Hamiltonian invariants.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/hllm-training-free-grpo.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/hllm-training-free-grpo.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-08-01',
      authors: ['Zoo Labs Foundation'],
      tags: ['HLLM', 'GRPO', 'Cost Reduction', 'Optimization'],
    },
    {
      id: 'zoo-dso',
      title: 'Zoo DSO: Decentralized Semantic Optimization',
      subtitle: 'Byzantine-Robust Prior Aggregation for Collective Intelligence',
      abstract: 'A decentralized protocol for aggregating AI model priors with Byzantine fault tolerance, enabling collective intelligence at network scale.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-dso.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-dso.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-10-28',
      authors: ['Zoo Labs Foundation'],
      tags: ['DSO', 'Byzantine Robust', 'Decentralized', 'Collective Intelligence'],
      relatedLinks: [
        { label: 'ZIP-001 Specification', url: 'https://github.com/zooai/zips/blob/main/ZIP-001-dso.md' },
        { label: 'Hanzo ASO (foundation)', url: 'https://github.com/hanzoai/papers' },
      ],
    },
    {
      id: 'experience-ledger-dso',
      title: 'Experience Ledger: Decentralized Semantic Optimization for LLMs',
      subtitle: 'Three-Layer Storage with 7680-Dim Embeddings',
      abstract: 'DSO with Byzantine-robust curation, three-layer storage, and 7680-dimensional embeddings for persistent learning.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/experience-ledger-dso.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/experience-ledger-dso.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-09-15',
      authors: ['Zoo Labs Foundation'],
      tags: ['DSO', 'Experience Ledger', 'Byzantine Robust'],
    },
    {
      id: 'zoo-experience-ledger',
      title: 'Zoo Experience Ledger',
      subtitle: 'Content-Addressable Semantic Memory',
      abstract: 'Content-addressable semantic memory system for decentralized AI with persistent learning across agents.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-experience-ledger.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-experience-ledger.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-09-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Experience Ledger', 'Semantic Memory', 'Content-Addressable'],
    },
    {
      id: 'experience-ledger',
      title: 'Experience Ledgers: Learning from Human-AI Interaction',
      subtitle: 'Persistent Semantic Memory',
      abstract: 'Persistent semantic memory from human-AI interaction for continuous learning and improvement.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/experience-ledger.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/experience-ledger.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-08-15',
      authors: ['Zoo Labs Foundation'],
      tags: ['Experience Ledger', 'Human-AI', 'Semantic Memory'],
    },
    {
      id: 'zip-002-zen-reranker',
      title: 'ZIP-002: Zen-Reranker Integration',
      subtitle: 'Native 7680-Dimensional Embeddings with BitDelta',
      abstract: 'Native 7680-dimensional embeddings with BitDelta compression (31.87x ratio) for decentralized semantic optimization.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zip-002-zen-reranker.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zip-002-zen-reranker.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-11-01',
      authors: ['Zoo Labs Foundation'],
      tags: ['ZIP-002', 'Zen-Reranker', 'Embeddings', 'BitDelta'],
    },
    {
      id: 'zoo-poai-consensus',
      title: 'Proof of AI: Consensus for Verifiable Compute',
      subtitle: 'Verifiable AI Compute Contribution',
      abstract: 'Consensus mechanism for verifying and rewarding AI compute contributions in decentralized networks.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-poai-consensus.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-poai-consensus.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-11-15',
      authors: ['Zoo Labs Foundation'],
      tags: ['PoAI', 'Consensus', 'Verifiable Compute'],
      relatedLinks: [
        { label: 'ZIP-002 Specification', url: 'https://github.com/zooai/zips/blob/main/ZIP-002-poai.md' },
      ],
    },
    {
      id: 'poai-consensus',
      title: 'Proof of AI: Consensus Mechanisms for ML Workloads',
      subtitle: 'ML-Optimized Consensus',
      abstract: 'Consensus mechanisms designed specifically for machine learning workloads and verifiable AI computation.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/poai-consensus.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/poai-consensus.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-11-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['PoAI', 'ML Consensus', 'Proof Systems'],
    },
    {
      id: 'zoo-agent-nft',
      title: 'Agent NFTs: Token Standard for Autonomous AI Agents',
      subtitle: 'AI Agent Tokenization',
      abstract: 'Token standard for AI agents with economic agency, autonomous operation, and decentralized governance.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-agent-nft.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-agent-nft.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-07-01',
      authors: ['Zoo Labs Foundation'],
      tags: ['Agent NFT', 'Token Standard', 'AI Agents'],
    },
    {
      id: 'agent-nft',
      title: 'Agent NFTs: Tokenized AI Ownership and Governance',
      subtitle: 'Governance Framework for AI Agents',
      abstract: 'Governance and ownership framework for tokenized AI agents with economic agency.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/agent-nft.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/agent-nft.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-07-15',
      authors: ['Zoo Labs Foundation'],
      tags: ['NFT', 'AI Ownership', 'Governance'],
    },
    {
      id: 'federated-dso',
      title: 'Federated DSO: Privacy-Preserving Distributed Learning',
      subtitle: 'Privacy-Preserving LLM Learning',
      abstract: 'Privacy-preserving distributed learning using federated DSO for LLMs across decentralized networks.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/federated-dso.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/federated-dso.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-12-01',
      authors: ['Zoo Labs Foundation'],
      tags: ['Federated', 'Privacy', 'Distributed Learning'],
    },
    {
      id: 'embedding-7680',
      title: 'High-Dimensional Embedding Spaces for Semantic Search',
      subtitle: 'The Case for 7680 Dimensions',
      abstract: 'The case for 7680-dimensional embedding spaces in semantic search for optimal retrieval quality.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/embedding-7680.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/embedding-7680.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2024-10-01',
      authors: ['Zoo Labs Foundation'],
      tags: ['Embeddings', '7680-Dim', 'Semantic Search'],
    },
    {
      id: 'conservation-ai',
      title: 'Conservation AI: Species Protection Systems',
      subtitle: 'AI for Wildlife Conservation',
      abstract: 'AI systems for wildlife conservation and species protection at scale.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-conservation-ai.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-conservation-ai.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Conservation', 'Wildlife', 'AI', 'Species Protection'],
    },
    {
      id: 'wildlife-tracking',
      title: 'Wildlife Tracking with Computer Vision',
      subtitle: 'Real-Time Animal Detection and Monitoring',
      abstract: 'Computer vision systems for real-time wildlife tracking, detection, and monitoring.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-wildlife-tracking.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-wildlife-tracking.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Wildlife', 'Tracking', 'Computer Vision', 'Monitoring'],
    },
    {
      id: 'habitat-modeling',
      title: 'AI Habitat Modeling',
      subtitle: 'Predictive Habitat Analysis and Restoration',
      abstract: 'AI-driven predictive habitat analysis and restoration planning for conservation efforts.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-habitat-modeling.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-habitat-modeling.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Habitat', 'Modeling', 'Prediction', 'Restoration'],
    },
    {
      id: 'species-classification',
      title: 'Deep Learning for Species Classification',
      subtitle: 'Multi-Modal Species Identification',
      abstract: 'Deep learning approaches for multi-modal species identification and classification.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-species-classification.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-species-classification.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Classification', 'Deep Learning', 'Species', 'Multi-Modal'],
    },
    {
      id: 'impact-bonds',
      title: 'Conservation Impact Bonds',
      subtitle: 'Tokenized Environmental Impact Finance',
      abstract: 'Tokenized environmental impact bonds for conservation finance and DeFi composability.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-impact-bonds.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-impact-bonds.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Impact Bonds', 'Conservation', 'DeFi', 'Environment'],
    },
    {
      id: 'carbon-credits',
      title: 'AI-Verified Carbon Credits',
      subtitle: 'Satellite-Validated Carbon Offset Protocol',
      abstract: 'AI-verified carbon credit protocol with satellite validation for transparent carbon offset markets.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-carbon-credits.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-carbon-credits.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Carbon Credits', 'Verification', 'Climate', 'Satellite'],
    },
    {
      id: 'dao-governance',
      title: 'Zoo DAO Governance',
      subtitle: 'Quadratic Voting and Scientific Governance',
      abstract: 'DAO governance framework with quadratic voting for scientific research coordination.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-dao-governance.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-dao-governance.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['DAO', 'Governance', 'Quadratic Voting', 'Science'],
    },
    {
      id: 'citizen-science',
      title: 'Citizen Science Platform',
      subtitle: 'Crowdsourced Data Collection for Conservation',
      abstract: 'Platform for crowdsourced scientific data collection supporting conservation research.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-citizen-science.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-citizen-science.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Citizen Science', 'Crowdsourcing', 'Data Collection'],
    },
    {
      id: 'educational-ai',
      title: 'Educational AI for Conservation',
      subtitle: 'Adaptive Learning for Environmental Education',
      abstract: 'Adaptive learning systems for environmental education and conservation awareness.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-educational-ai.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-educational-ai.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Education', 'AI', 'Conservation', 'Learning'],
    },
    {
      id: 'research-coordination',
      title: 'Decentralized Research Coordination',
      subtitle: 'Multi-Institution Scientific Collaboration',
      abstract: 'Decentralized coordination framework for multi-institution scientific collaboration.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-research-coordination.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-research-coordination.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Research', 'Coordination', 'Decentralized', 'Collaboration'],
    },
    {
      id: 'data-commons',
      title: 'Open Data Commons for Conservation',
      subtitle: 'Shared Scientific Data Infrastructure',
      abstract: 'Open data commons infrastructure for shared scientific datasets supporting conservation research.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-data-commons.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-data-commons.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Data Commons', 'Open Data', 'Infrastructure', 'Science'],
    },
    {
      id: 'mobile-inference',
      title: 'Mobile AI Inference for Field Research',
      subtitle: 'Edge AI for Wildlife Monitoring',
      abstract: 'Mobile AI inference for field research with edge deployment for wildlife monitoring.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-mobile-inference.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-mobile-inference.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Mobile', 'Inference', 'Edge AI', 'Field Research'],
    },
    {
      id: 'federated-wildlife',
      title: 'Federated Learning for Wildlife Data',
      subtitle: 'Privacy-Preserving Cross-Organization Learning',
      abstract: 'Federated learning for privacy-preserving cross-organization wildlife data analysis.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-federated-wildlife.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-federated-wildlife.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Federated Learning', 'Privacy', 'Wildlife', 'Cross-Org'],
    },
    {
      id: 'satellite-ecology',
      title: 'Satellite Ecology with Deep Learning',
      subtitle: 'Remote Sensing for Ecosystem Monitoring',
      abstract: 'Deep learning applied to satellite remote sensing for ecosystem monitoring and ecological analysis.',
      pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-satellite-ecology.pdf',
      latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-satellite-ecology.tex',
      githubUrl: 'https://github.com/zooai/papers',
      date: '2025-02-20',
      authors: ['Zoo Labs Foundation'],
      tags: ['Satellite', 'Ecology', 'Remote Sensing', 'Deep Learning'],
    },
  ],
}
